dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - gcc-6
      - g++-6
      - clang-4.0
      - ninja-build

matrix:
    include:
        - language: cpp
          compiler: gcc
          install:
              - git submodule update --init --recursive
          before_script:
              - mkdir build
              - cd build
              - export CC=gcc-6
              - export CXX=g++-6
              - cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          script:
              - cmake --build . -- -j4
              - ctest
        - language: cpp
          compiler: clang
          install:
              - git submodule update --init --recursive
          before_script:
              - mkdir build
              - cd build
              - export CC=clang-4.0
              - export CXX=clang++-4.0
              - cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          script:
              - cmake --build . -- -j4
              - ctest
