dist: xenial

matrix:
    include:
        - language: cpp
          compiler: gcc
          addons:
              apt:
                  sources:
                    - ubuntu-toolchain-r-test
                  packages:
                    - gcc-6
                    - g++-6
                    - ninja-build

          install:
              - git submodule update --init --recursive
          before_script:
              - mkdir build
              - cd build
              - export CC=gcc-6
              - export CXX=g++-6
              - cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          script:
              - cmake --build . -- -j4
              - ctest
        - language: cpp
          compiler: clang
          addons:
              apt:
                  sources:
                    - llvm-toolchain-xenial-8
                  packages:
                    - clang-8
                    - ninja-build
          install:
              - git submodule update --init --recursive
          before_script:
              - mkdir build
              - cd build
              - export CC=clang-8
              - export CXX=clang++-8
              - cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          script:
              - cmake --build . -- -j4
              - ctest
        - language: java
          jdk: openjdk11
          install:
              - cd programming/adaptive-java
              - ./gradlew assemble
          script:
              - ./gradlew check
